name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{secrets.DO_HOST}}
          username: ${{secrets.DO_USERNAME}}
          key: ${{secrets.DO_SSH_KEY}}
          script: |
            # Navigate to the application directory
            cd ~/mysecondbrain.info-BE

            #set all the env variables here
            set -o allexport; source ~/.env.production; set +o allexport

            #stop and remove the current containers
            docker compose -f docker-compose.production.yml down
            
            # Pull the latest code
            git checkout main
            git pull
                        
            # Start the containers with the newly built image
            docker compose -f docker-compose.production.yml up -d --build
            
            # Clean up unused Docker resources (keep images used in last 24h)
            docker system prune -a --filter "until=24h" -f 