name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mysecondbrain-api:latest

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            # Navigate to the application directory
            cd ~/mysecondbrain.info-BE
            
            # Pull the latest code
            git pull
            
            # Pull the latest Docker image
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mysecondbrain-api:latest
            
            # Stop and remove the current containers
            docker-compose down
            
            # Start the containers again with the new image
            docker-compose up -d
            
            # Clean up unused Docker resources
            docker system prune -af 