name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{secrets.DO_HOST}}
          username: ${{secrets.DO_USERNAME}}
          key: ${{secrets.DO_SSH_KEY}}
          script: |
            # Navigate to the application directory
            cd ~/mysecondbrain.info-BE

            # Load environment if exists or continue
            [ -f ".env.production" ] && set -o allexport; source .env.production; set +o allexport

            # Pull the latest code
            git checkout main
            git pull
            
            # Make scripts executable
            chmod +x ./nginx/init-letsencrypt.sh ./nginx/renew-certs.sh ./nginx/setup-renewal-cron.sh
            
            # Create/update SSL config if needed
            if [ ! -f ".env.ssl" ]; then
              echo "Creating SSL configuration..."
              echo "DOMAIN=api.mysecondbrain.info" > .env.ssl
              echo "EMAIL=aquib.jansher@gmail.com" >> .env.ssl
              echo "STAGING=0" >> .env.ssl
              
              mkdir -p ./nginx/logs ./data/certbot/www ./data/certbot/conf
              
              # Run initial SSL setup
              ./nginx/init-letsencrypt.sh
              ./nginx/setup-renewal-cron.sh
            else
              # Renew certificates if necessary
              ./nginx/renew-certs.sh
              
              # Restart containers
              docker compose --env-file .env.ssl -f docker-compose.production.yml down
              docker compose --env-file .env.ssl -f docker-compose.production.yml up -d --build
            fi
            
            # Clean up
            docker system prune -a --filter "until=24h" -f 